### PR TITLE
Change splitting

### PR DESCRIPTION
**Pull request by MartinSchere**
Have the option to split UTxOs in an eternl-like fashion.

The idea is to have something like: 

```ts
const tx = await Tx.new().config({ enableChangeSplitting:true }) // (...)
```

And have the rest of the magic when calling `complete()`.

### CODE REVIEW

**Comment by MartinSchere** [comment]
Note: This contains the changes for #7

**Comment by alessandrokonrad** [comment]
These changes should be rather in the serialization-lib.

**Comment by MartinSchere** [comment]
The code I already have is in TS. We can move it to the serialization lib tho to keep things organized & fast

**Comment by alessandrokonrad** [comment]
The add_change_if_needes function needs to be improved anyway. And the coin selection as well. Then I think everything we do in lucid should work pretty well

**Comment by MartinSchere** [comment]
I agree, they do need some work.

Adding this modification to `add_change_if_needed` is way easier, but It should be opt-in.

Then we can create our own coin selection strategy that's a mix between randomImprove and largestFirst as a temporary solution.

**Comment by MartinSchere** [comment]
We are moving this to rust!

**Pull request closed without merging**
